version: "3.8"

services:
  postgre-db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./postgre:/var/lib/postgresql/data
    ports:
      - 5432:5432
